# Generated by Django 4.1.1 on 2023-02-14 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telemed", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="email",
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="patient",
            name="username",
            field=models.CharField(max_length=10),
        ),
    ]
