# Generated by Django 4.1.1 on 2023-02-16 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Hostels", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="login", name="matric_no", field=models.CharField(max_length=25),
        ),
    ]
