# Generated by Django 4.1.1 on 2023-02-16 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Hostels", "0002_alter_login_matric_no"),
    ]

    operations = [
        migrations.CreateModel(
            name="Hostel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description_image1", models.ImageField(upload_to="media/")),
                ("hostel_description", models.TextField()),
                ("occupied", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT, to="Hostels.login"
                    ),
                ),
            ],
        ),
    ]
