# Generated by Django 4.1.1 on 2023-02-16 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Hostels", "0003_hostel"),
    ]

    operations = [
        migrations.RenameField(
            model_name="hostel", old_name="user", new_name="assigned_to",
        ),
        migrations.AddField(
            model_name="hostel", name="paid", field=models.BooleanField(default=False),
        ),
    ]
