# Generated by Django 4.1.1 on 2023-02-16 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Hostels", "0004_rename_user_hostel_assigned_to_hostel_paid"),
    ]

    operations = [
        migrations.AddField(
            model_name="hostel",
            name="name",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
